"""시·군·구 이름 사전. engine/scripts/build_region_vocab.py 가 기관 주소에서 만든다 — 손으로 고치지 않는다."""

# 시·군·구 이름 -> 그 이름이 쓰이는 시·도들(같은 이름이 여러 시·도에 있다: 중구·북구·동구 …)
SIGUNGU_PARENTS: dict[str, frozenset[str]] = {
    '가평군': frozenset(['경기도']),
    '강남구': frozenset(['서울특별시']),
    '강동구': frozenset(['서울특별시']),
    '강릉시': frozenset(['강원도', '강원특별자치도']),
    '강북구': frozenset(['서울특별시']),
    '강서구': frozenset(['부산광역시', '서울특별시']),
    '강진군': frozenset(['전남광주통합특별시', '전라남도']),
    '강화군': frozenset(['경기도', '인천광역시']),
    '거제군': frozenset(['경상남도']),
    '거제시': frozenset(['경상남도']),
    '거창군': frozenset(['경상남도']),
    '검단구': frozenset(['인천광역시']),
    '경산군': frozenset(['경상북도']),
    '경산시': frozenset(['경상북도']),
    '경주군': frozenset(['경상북도']),
    '경주시': frozenset(['경상북도']),
    '계룡시': frozenset(['충청남도']),
    '계양구': frozenset(['인천광역시']),
    '고령군': frozenset(['경상북도']),
    '고성군': frozenset(['강원도', '강원특별자치도', '경상남도']),
    '고양시': frozenset(['경기도']),
    '고창군': frozenset(['강원특별자치도', '전라북도', '전북특별자치도']),
    '고흥군': frozenset(['전남광주통합특별시', '전라남도']),
    '곡성군': frozenset(['전남광주통합특별시', '전라남도']),
    '공주시': frozenset(['충청남도']),
    '과천시': frozenset(['경기도']),
    '관악구': frozenset(['서울특별시']),
    '광명시': frozenset(['경기도']),
    '광산구': frozenset(['광주광역시', '전남광주통합특별시']),
    '광산군': frozenset(['전라남도']),
    '광양군': frozenset(['전라남도']),
    '광양시': frozenset(['전남광주통합특별시', '전라남도']),
    '광주군': frozenset(['경기도']),
    '광주시': frozenset(['경기도']),
    '광진구': frozenset(['서울특별시']),
    '괴산군': frozenset(['충청북도']),
    '구례군': frozenset(['전라남도']),
    '구로구': frozenset(['서울특별시']),
    '구리시': frozenset(['경기도']),
    '구미시': frozenset(['경상북도']),
    '군산시': frozenset(['강원특별자치도', '전라북도', '전북특별자치도']),
    '군위군': frozenset(['경상북도', '대구광역시']),
    '군포시': frozenset(['경기도']),
    '금릉군': frozenset(['경상북도']),
    '금산군': frozenset(['충청남도']),
    '금정구': frozenset(['부산광역시']),
    '금천구': frozenset(['서울특별시']),
    '기장군': frozenset(['부산광역시']),
    '김제군': frozenset(['전라북도']),
    '김제시': frozenset(['강원특별자치도', '전라북도', '전북특별자치도']),
    '김천시': frozenset(['경상북도']),
    '김포군': frozenset(['경기도']),
    '김포시': frozenset(['경기도']),
    '김해군': frozenset(['경상남도']),
    '김해시': frozenset(['경상남도']),
    '나주군': frozenset(['전라남도']),
    '나주시': frozenset(['전남광주통합특별시', '전라남도']),
    '남구': frozenset(['광주광역시', '대구광역시', '부산광역시', '울산광역시', '인천광역시', '전남광주통합특별시']),
    '남동구': frozenset(['인천광역시']),
    '남양주군': frozenset(['경기도']),
    '남양주시': frozenset(['경기도']),
    '남원군': frozenset(['전라북도']),
    '남원시': frozenset(['강원특별자치도', '전라북도', '전북특별자치도']),
    '남해군': frozenset(['경상남도']),
    '노원구': frozenset(['서울특별시']),
    '논산군': frozenset(['충청남도']),
    '논산시': frozenset(['충청남도']),
    '단양군': frozenset(['충청북도']),
    '달서구': frozenset(['대구광역시']),
    '달성군': frozenset(['경상북도', '대구광역시']),
    '담양군': frozenset(['전남광주통합특별시', '전라남도']),
    '당진군': frozenset(['충청남도']),
    '당진시': frozenset(['충청남도']),
    '대덕구': frozenset(['대전광역시']),
    '대전시': frozenset(['충청남도']),
    '대천시': frozenset(['충청남도']),
    '도봉구': frozenset(['서울특별시']),
    '동광양시': frozenset(['전라남도']),
    '동구': frozenset(['광주광역시', '대구광역시', '대전광역시', '부산광역시', '울산광역시', '인천광역시', '전남광주통합특별시']),
    '동대문구': frozenset(['서울특별시']),
    '동두천시': frozenset(['경기도']),
    '동래구': frozenset(['부산광역시']),
    '동작구': frozenset(['서울특별시']),
    '동해시': frozenset(['강원도', '강원특별자치도']),
    '마산시': frozenset(['경상남도']),
    '마포구': frozenset(['서울특별시']),
    '명주군': frozenset(['강원도']),
    '목포시': frozenset(['전남광주통합특별시', '전라남도']),
    '무안군': frozenset(['전남광주통합특별시', '전라남도']),
    '무주군': frozenset(['강원특별자치도', '전라북도', '전북특별자치도']),
    '문경군': frozenset(['경상북도']),
    '문경시': frozenset(['경상북도']),
    '미금시': frozenset(['경기도']),
    '미추홀구': frozenset(['인천광역시']),
    '밀양군': frozenset(['경상남도']),
    '밀양시': frozenset(['경상남도']),
    '보령시': frozenset(['충청남도']),
    '보성군': frozenset(['전남광주통합특별시', '전라남도']),
    '보은군': frozenset(['충청북도']),
    '봉화군': frozenset(['경상북도']),
    '부산진구': frozenset(['부산광역시']),
    '부산진군': frozenset(['부산광역시']),
    '부안군': frozenset(['강원특별자치도', '전라북도', '전북특별자치도']),
    '부여군': frozenset(['충청남도']),
    '부천시': frozenset(['경기도']),
    '부평구': frozenset(['인천광역시']),
    '북구': frozenset(['광주광역시', '대구광역시', '부산광역시', '울산광역시', '인천광역시', '전남광주통합특별시']),
    '사상구': frozenset(['부산광역시']),
    '사천군': frozenset(['경상남도']),
    '사천시': frozenset(['경상남도']),
    '사하구': frozenset(['부산광역시']),
    '산청군': frozenset(['경상남도']),
    '삼척군': frozenset(['강원도']),
    '삼척시': frozenset(['강원도', '강원특별자치도']),
    '삼천포시': frozenset(['경상남도']),
    '상주군': frozenset(['경상북도']),
    '상주시': frozenset(['경상북도']),
    '서구': frozenset(['광주광역시', '대구광역시', '대전광역시', '부산광역시', '인천광역시', '전남광주통합특별시']),
    '서귀포시': frozenset(['제주특별자치도']),
    '서대문구': frozenset(['서울특별시']),
    '서산구': frozenset(['부산광역시']),
    '서산시': frozenset(['충청남도']),
    '서천군': frozenset(['충청남도']),
    '서초구': frozenset(['서울특별시']),
    '서해구': frozenset(['인천광역시']),
    '선산군': frozenset(['경상북도']),
    '성남시': frozenset(['경기도']),
    '성동구': frozenset(['서울특별시']),
    '성북구': frozenset(['서울특별시']),
    '성주군': frozenset(['경상북도']),
    '속초시': frozenset(['강원도', '강원특별자치도']),
    '송탄시': frozenset(['경기도']),
    '송파구': frozenset(['서울특별시']),
    '수성구': frozenset(['대구광역시']),
    '수영구': frozenset(['부산광역시']),
    '수원시': frozenset(['경기도']),
    '순창군': frozenset(['전라북도', '전북특별자치도']),
    '순천시': frozenset(['전남광주통합특별시', '전라남도']),
    '승주군': frozenset(['전라남도']),
    '시흥군': frozenset(['경기도']),
    '시흥시': frozenset(['경기도']),
    '신안군': frozenset(['전남광주통합특별시', '전라남도']),
    '아산군': frozenset(['충청남도']),
    '아산시': frozenset(['충청남도']),
    '안동군': frozenset(['경상북도']),
    '안동시': frozenset(['경상북도']),
    '안산시': frozenset(['경기도']),
    '안성군': frozenset(['경기도']),
    '안성시': frozenset(['경기도']),
    '안양시': frozenset(['경기도']),
    '양구군': frozenset(['강원도', '강원특별자치도']),
    '양산군': frozenset(['경상남도']),
    '양산시': frozenset(['경상남도']),
    '양양군': frozenset(['강원도', '강원특별자치도']),
    '양주군': frozenset(['경기도']),
    '양주시': frozenset(['경기도']),
    '양천구': frozenset(['서울특별시']),
    '양평군': frozenset(['경기도']),
    '여수시': frozenset(['전남광주통합특별시', '전라남도']),
    '여주군': frozenset(['경기도']),
    '여주시': frozenset(['경기도']),
    '여천군': frozenset(['전라남도']),
    '여천시': frozenset(['전라남도']),
    '연기군': frozenset(['충청남도']),
    '연수구': frozenset(['인천광역시']),
    '연제구': frozenset(['부산광역시']),
    '연천군': frozenset(['경기도']),
    '영광군': frozenset(['전라남도']),
    '영덕군': frozenset(['경상북도']),
    '영도구': frozenset(['부산광역시']),
    '영동군': frozenset(['충청북도']),
    '영등포구': frozenset(['서울특별시']),
    '영암군': frozenset(['전남광주통합특별시', '전라남도']),
    '영양군': frozenset(['경상북도']),
    '영월군': frozenset(['강원도', '강원특별자치도']),
    '영일군': frozenset(['경상북도']),
    '영종구': frozenset(['인천광역시']),
    '영주시': frozenset(['경상북도']),
    '영천군': frozenset(['경상북도']),
    '영천시': frozenset(['경상북도']),
    '영풍군': frozenset(['경상북도']),
    '예산군': frozenset(['충청남도']),
    '예천군': frozenset(['경상북도']),
    '오산시': frozenset(['경기도']),
    '옥구군': frozenset(['전라북도']),
    '옥천군': frozenset(['충청북도']),
    '온양시': frozenset(['충청남도']),
    '옹진군': frozenset(['경기도', '인천광역시']),
    '완도군': frozenset(['전남광주통합특별시', '전라남도']),
    '완주군': frozenset(['강원특별자치도', '전라북도', '전북특별자치도']),
    '용산구': frozenset(['서울특별시']),
    '용인군': frozenset(['경기도']),
    '용인시': frozenset(['경기도']),
    '울릉군': frozenset(['경상북도']),
    '울산군': frozenset(['경상남도']),
    '울산시': frozenset(['경상남도']),
    '울주구': frozenset(['울산광역시']),
    '울주군': frozenset(['울산광역시']),
    '울진군': frozenset(['경상북도']),
    '웅진군': frozenset(['경기도']),
    '원주군': frozenset(['강원도']),
    '원주시': frozenset(['강원도', '강원특별자치도']),
    '월성군': frozenset(['경상북도']),
    '유성구': frozenset(['대전광역시']),
    '은평구': frozenset(['서울특별시']),
    '음성군': frozenset(['충청북도']),
    '의령군': frozenset(['경상남도']),
    '의성군': frozenset(['경상북도']),
    '의왕시': frozenset(['경기도']),
    '의정부시': frozenset(['경기도']),
    '의창군': frozenset(['경상남도']),
    '이리시': frozenset(['전라북도']),
    '이천군': frozenset(['경기도']),
    '이천시': frozenset(['경기도']),
    '익산군': frozenset(['전라북도']),
    '익산시': frozenset(['강원특별자치도', '전라북도', '전북특별자치도']),
    '인제군': frozenset(['강원도', '강원특별자치도']),
    '임실군': frozenset(['강원특별자치도', '전라북도', '전북특별자치도']),
    '장성군': frozenset(['전남광주통합특별시', '전라남도']),
    '장수군': frozenset(['강원특별자치도', '전라북도', '전북특별자치도']),
    '장승포시': frozenset(['경상남도']),
    '장흥군': frozenset(['전남광주통합특별시', '전라남도']),
    '전주시': frozenset(['강원특별자치도', '전라북도', '전북특별자치도']),
    '점촌시': frozenset(['경상북도']),
    '정선군': frozenset(['강원도', '강원특별자치도']),
    '정읍군': frozenset(['전라북도']),
    '정읍시': frozenset(['강원특별자치도', '전라북도', '전북특별자치도']),
    '정주시': frozenset(['전라북도']),
    '제물포구': frozenset(['인천광역시']),
    '제주시': frozenset(['제주특별자치도']),
    '제천군': frozenset(['충청북도']),
    '제천시': frozenset(['충청북도']),
    '종로구': frozenset(['서울특별시']),
    '중구': frozenset(['대구광역시', '대전광역시', '부산광역시', '서울특별시', '울산광역시', '인천광역시']),
    '중랑구': frozenset(['서울특별시']),
    '중원군': frozenset(['충청북도']),
    '증평군': frozenset(['충청북도']),
    '진구': frozenset(['부산광역시']),
    '진도군': frozenset(['전남광주통합특별시', '전라남도']),
    '진안군': frozenset(['강원특별자치도', '전라북도', '전북특별자치도']),
    '진양군': frozenset(['경상남도']),
    '진주시': frozenset(['경상남도']),
    '진천군': frozenset(['충청북도']),
    '진해시': frozenset(['경상남도']),
    '창녕군': frozenset(['경상남도']),
    '창원군': frozenset(['경상남도']),
    '창원시': frozenset(['경상남도']),
    '천안시': frozenset(['충청남도']),
    '철원군': frozenset(['강원도', '강원특별자치도']),
    '청도군': frozenset(['경상북도']),
    '청송군': frozenset(['경상북도']),
    '청양군': frozenset(['충청남도']),
    '청원군': frozenset(['충청북도']),
    '청주시': frozenset(['충청북도']),
    '춘천시': frozenset(['강원도', '강원특별자치도']),
    '충무시': frozenset(['경상남도']),
    '충주시': frozenset(['충청북도']),
    '칠곡군': frozenset(['경상북도']),
    '태백시': frozenset(['강원도', '강원특별자치도']),
    '태안군': frozenset(['충청남도']),
    '택백시': frozenset(['강원도']),
    '통영군': frozenset(['경상남도']),
    '통영시': frozenset(['경상남도']),
    '특별시': frozenset(['서울특별시']),
    '파주군': frozenset(['경기도']),
    '파주시': frozenset(['경기도']),
    '평창군': frozenset(['강원도', '강원특별자치도']),
    '평택군': frozenset(['경기도']),
    '평택시': frozenset(['경기도']),
    '포천군': frozenset(['경기도']),
    '포천시': frozenset(['경기도']),
    '포항시': frozenset(['경상북도']),
    '하남시': frozenset(['경기도']),
    '하동군': frozenset(['경상남도']),
    '함안군': frozenset(['경상남도']),
    '함양군': frozenset(['경상남도']),
    '함평군': frozenset(['전남광주통합특별시', '전라남도']),
    '합천군': frozenset(['경상남도']),
    '해남군': frozenset(['전남광주통합특별시', '전라남도']),
    '해운대구': frozenset(['부산광역시']),
    '홍성군': frozenset(['충청남도']),
    '홍천군': frozenset(['강원도', '강원특별자치도']),
    '화성군': frozenset(['경기도']),
    '화성시': frozenset(['경기도']),
    '화순군': frozenset(['전남광주통합특별시', '전라남도']),
    '화천군': frozenset(['강원도', '강원특별자치도']),
    '횡성군': frozenset(['강원도', '강원특별자치도']),
}
